version: "3.8"

services:
  app:
    build: .
    container_name: podman_test_app
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./app:/app/app:Z

  mysql:
    image: mysql:8.4
    container_name: podman_test_mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql:Z
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local

networks:
  default:
    driver: bridge
